/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PopularIndexRouteImport } from './routes/popular/index'
import { Route as HotdealIndexRouteImport } from './routes/hotdeal/index'
import { Route as CategoryIndexRouteImport } from './routes/category/index'
import { Route as CategoryCategoryNameRouteImport } from './routes/category/$categoryName'
import { Route as ProductProductIdIndexRouteImport } from './routes/product/$productId/index'

const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PopularIndexRoute = PopularIndexRouteImport.update({
  id: '/popular/',
  path: '/popular/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotdealIndexRoute = HotdealIndexRouteImport.update({
  id: '/hotdeal/',
  path: '/hotdeal/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIndexRoute = CategoryIndexRouteImport.update({
  id: '/category/',
  path: '/category/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryNameRoute = CategoryCategoryNameRouteImport.update({
  id: '/category/$categoryName',
  path: '/category/$categoryName',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdIndexRoute = ProductProductIdIndexRouteImport.update({
  id: '/product/$productId/',
  path: '/product/$productId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/category/$categoryName': typeof CategoryCategoryNameRoute
  '/category': typeof CategoryIndexRoute
  '/hotdeal': typeof HotdealIndexRoute
  '/popular': typeof PopularIndexRoute
  '/product/$productId': typeof ProductProductIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/category/$categoryName': typeof CategoryCategoryNameRoute
  '/category': typeof CategoryIndexRoute
  '/hotdeal': typeof HotdealIndexRoute
  '/popular': typeof PopularIndexRoute
  '/product/$productId': typeof ProductProductIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/category/$categoryName': typeof CategoryCategoryNameRoute
  '/category/': typeof CategoryIndexRoute
  '/hotdeal/': typeof HotdealIndexRoute
  '/popular/': typeof PopularIndexRoute
  '/product/$productId/': typeof ProductProductIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/category/$categoryName'
    | '/category'
    | '/hotdeal'
    | '/popular'
    | '/product/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/category/$categoryName'
    | '/category'
    | '/hotdeal'
    | '/popular'
    | '/product/$productId'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/category/$categoryName'
    | '/category/'
    | '/hotdeal/'
    | '/popular/'
    | '/product/$productId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CategoryCategoryNameRoute: typeof CategoryCategoryNameRoute
  CategoryIndexRoute: typeof CategoryIndexRoute
  HotdealIndexRoute: typeof HotdealIndexRoute
  PopularIndexRoute: typeof PopularIndexRoute
  ProductProductIdIndexRoute: typeof ProductProductIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/popular/': {
      id: '/popular/'
      path: '/popular'
      fullPath: '/popular'
      preLoaderRoute: typeof PopularIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotdeal/': {
      id: '/hotdeal/'
      path: '/hotdeal'
      fullPath: '/hotdeal'
      preLoaderRoute: typeof HotdealIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/': {
      id: '/category/'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof CategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categoryName': {
      id: '/category/$categoryName'
      path: '/category/$categoryName'
      fullPath: '/category/$categoryName'
      preLoaderRoute: typeof CategoryCategoryNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId/': {
      id: '/product/$productId/'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CategoryCategoryNameRoute: CategoryCategoryNameRoute,
  CategoryIndexRoute: CategoryIndexRoute,
  HotdealIndexRoute: HotdealIndexRoute,
  PopularIndexRoute: PopularIndexRoute,
  ProductProductIdIndexRoute: ProductProductIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
